# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.box_version = "= 20211001.0.0 "
  config.vm.synced_folder ".", "/vagrant"
  config.vm.network "forwarded_port", guest: 8000, host: 8000, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 8080, host: 8080, host_ip: "127.0.0.1"
  config.vm.network "forwarded_port", guest: 5000, host: 5000, host_ip: "127.0.0.1"

  # Work around disconnected virtual network cable.
  config.vm.provider "hyperv" do |vb|
    vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
    vb.gui = true
  end


  config.vm.provision "shell", inline: <<-SHELL
    apt-get -qqy update

    DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" upgrade
    apt-get update
	
    # Python 3 compatible version
    # Original solved problem to install python and pip : https://askubuntu.com/questions/1317411/pip-version-returns-syntaxerror-invalid-syntax-after-installation
    # Uninstall incompatible PIP provided by distro repository
    sudo apt remove --purge python3-pip
    # Download pip version compatible with Python version 3.4
    curl -O https://bootstrap.pypa.io/pip/3.4/get-pip.py
    # Install pip
    sudo python3 get-pip.py
    # Upgrade pip to ensure 
    sudo python3 -m pip install --upgrade "pip < 19.2"
    
    # Install python packages
    # Use --user after the python package name to store the package in the right directory
    pip3 install numpy --user
    pip3 install flask --user
    
    # Install postgreSQL and python package:
    sudo apt-get update
    sudo apt-get install postgresql postgresql-contrib
    sudo apt-get install libpq-dev
    sudo apt-get install python3-dev
    sudo apt-get install python3-psycopg2


    apt-get -qqy install make zip unzip postgresql
    su postgres -c 'createuser -dRS vagrant'
    su vagrant -c 'createdb'
    su vagrant -c 'createdb news'

    vagrantTip="[35m[1mThe shared directory is located at /vagrant\\nTo access your shared files: cd /vagrant[m"
    echo -e $vagrantTip > /etc/motd

    wget http://download.redis.io/redis-stable.tar.gz
    tar xvzf redis-stable.tar.gz
    cd redis-stable
    make
    make install

    echo "Done installing your virtual machine!"
  SHELL
end
