"""Add password_salt column to user table

Revision ID: d36e6053cdfe
Revises: 
Create Date: 2023-09-25 22:19:27.937733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd36e6053cdfe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_salt', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_column('user', 'password_salt')
    # ### end Alembic commands ###
    pass
